Vergleich der Tracking Methoden
ar-exhibition/documentation pull request #2
Opened 2020-11-09 19:36 UTC by marlon360

2020-11-10 17:16 UTC, codebaard commented on Dokumentation.tex
> +  Weitere User der App können dann die Assets exakt so wiederherstellen, wie sie im Vorhinein gespeichert wurden.
"wie sie vorab" gespeichert wurden fände ich eine elegantere formulierung.

2020-11-10 17:19 UTC, codebaard commented on Dokumentation.tex
> +  Eine weitere Möglichkeit um die Positionen der echten Welt mit der AR Welt zu synchronisieren sind \textit{Image Marker}. Meist werden Bild Marker dazu genutzt 3D Objekte direkt mit einem Bild zu v
Image Marker vs Bild Marker ist ambivalent irgendwie. Ich fände es besser, wenn du dich für eine Nomenklatur entscheidest.

2020-11-10 17:22 UTC, codebaard commented on Dokumentation.tex
> +  Der Vorteil dieses Ansatzes ist es, dass die Genauigkeit im Bereich der Image Marker sehr hoch ist und die Marker billig produziert werden können und ohne Strom betrieben werden.
billger => günstiger ?

2020-11-10 17:23 UTC, codebaard commented on Dokumentation.tex
> +  Durch die Synchronisierung besonders markanter Stellen in der Umgebung (Feature Points) kann die Position und Rotation in der realen Welt sehr genau wiederhergestellt werden.
featurepoints => italic?

2020-11-10 17:24 UTC, codebaard commented on Dokumentation.tex
> +  Das gleiche Prinzip kann auch auf Räume angewandt werden. Dazu müssen zunächst die Feature Points aus einem Raum extrahiert werden und dann bei der Wiederherstllung verglichen werden.
2x "werden" => umformulieren?

2020-11-10 17:26 UTC, codebaard commented on Dokumentation.tex
> +  Wir haben uns für das \textit{Visual Positioning System} entschieden, da wir dadurch konstant gutes Tracking versichern können und
versichern => garantieren ?

2020-11-10 17:28 UTC, codebaard commented on Dokumentation.tex
> +  Wenn nun ein Besucher die App nutzt, wird diese Binärdatei auf das Gerät geladen.
"Binärdatei" ist eine für den Kontext dieses Absatzes unpassend finde ich. Vllt nehmen wir hier die Formulierung "Datensatz"?

2020-11-10 17:32 UTC, codebaard requested changes
pls consider annotations.

2020-11-11 11:30 UTC, marlon360 commented on Dokumentation.tex
> +  Wir haben uns für das \textit{Visual Positioning System} entschieden, da wir dadurch konstant gutes Tracking versichern können und
Das war das Wort, was ich gesucht habe 😄

2020-11-11 15:20 UTC, codebaard approved these changes

2020-11-11 15:22 UTC, merged